[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Kunter-Bunt/"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "Linked In"
url = "https://www.linkedin.com/in/marius-wodtke/"

[social.params]
icon = "brand-linkedin"