[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Kunter-Bunt/"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/marius-wodtke/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "mvp"
name = "Microsoft MVP"
url = "https://mvp.microsoft.com/en-US/MVP/profile/e4ace20d-ed50-4d7d-b140-4759582cf1c3"

[social.params]
icon = "MVP_Badge_Avatar_Secondary_White_RGB"