# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true

[footer]
since = 2023
customText = "This site is owned by Marius Wodtke, Marktgasse 21-23/27, 1090 Wien, Austria. All rights reserved."

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = ""
subtitle = "Hi, I'm Marius, Consultant for Dynamics 365 CE at Avanade. I specialize in integrating Dynamics with other systems."

[sidebar.avatar]
enabled = true
local = true
src = "images/MariusWodtke.png"